name: CI/CD Pipeline for Microfrontend Portals

on:
  push:
    branches:
      - development
      - student-development
      - admin-development
      - judges-development
      - organization-development

jobs:
  ci:
    name: Run Tests & Build Affected Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Run Affected Tests
        run: npx nx affected:test --base=origin/main

      - name: Build Affected Projects
        run: npx nx affected:build --base=origin/main

  deploy_student:
    name: Deploy Student Portal
    needs: ci
    if: github.ref == 'refs/heads/student-development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Student Portal
        run: npx nx build student-portal

      - name: Deploy Student Portal to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_TOTAL }}
          script: |
            cd /path/to/deployment/folder
            rm -rf student-portal
            mkdir student-portal
            cp -r $GITHUB_WORKSPACE/dist/student-portal ./student-portal
            # Optionally, restart services or run additional commands

  deploy_admin:
    name: Deploy Admin Portal
    needs: ci
    if: github.ref == 'refs/heads/admin-development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Admin Portal
        run: npx nx build admin-portal

      - name: Deploy Admin Portal to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_TOTAL }}
          script: |
            cd /path/to/deployment/folder
            rm -rf admin-portal
            mkdir admin-portal
            cp -r $GITHUB_WORKSPACE/dist/admin-portal ./admin-portal

  deploy_judges:
    name: Deploy Judges Portal
    needs: ci
    if: github.ref == 'refs/heads/judges-development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Judges Portal
        run: npx nx build judges-portal

      - name: Deploy Judges Portal to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_TOTAL }}
          script: |
            cd /path/to/deployment/folder
            rm -rf judges-portal
            mkdir judges-portal
            cp -r $GITHUB_WORKSPACE/dist/judges-portal ./judges-portal

  deploy_organization:
    name: Deploy Organization Portal
    needs: ci
    if: github.ref == 'refs/heads/organization-development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Organization Portal
        run: npx nx build organization-portal

      - name: Deploy Organization Portal to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_TOTAL }}
          script: |
            cd /path/to/deployment/folder
            rm -rf organization-portal
            mkdir organization-portal
            cp -r $GITHUB_WORKSPACE/dist/organization-portal ./organization-portal

  deploy_host:
    name: Deploy Host App (Algoed)
    needs: ci
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Build Host App
        run: npx nx build host-app

      - name: Deploy Host App to EC2
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_IP_TEST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY_TOTAL }}
          script: |
            cd /path/to/deployment/folder
            rm -rf host-app
            mkdir host-app
            cp -r $GITHUB_WORKSPACE/dist/host-app ./host-app
            # Restart or refresh the host service as required
